function [fitresult, gof] = Lowess2DFit(col, row, res_x,span)
%CREATEFIT(COL,ROW,RES_X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : col
%      Y Input : row
%      Z Output: res_x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Jan-2017 14:56:43


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( col, row, res_x );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Span = span;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'res_x vs. col, row', 'Location', 'NorthEast' );
% % Label axes
% xlabel col
% ylabel row
% zlabel res_x
% grid on
% view( -88.7, 90.0 );


