function [fitresult, gof] = Interpol2DFunc(col, row, res_x)
%CREATEFIT(COL,ROW,RES_X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : col
%      Y Input : row
%      Z Output: res_x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Jan-2017 14:18:11


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( col, row, res_x );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'res_x vs. col, row', 'Location', 'NorthEast' );
% Label axes
xlabel col
ylabel row
zlabel res_x
grid on
view( -89.9, 83.6 );


